resolver: lts-6.4

packages:
  - '.'

  - location: ../amqp-client
    extra-dep: true

  - location:
      git: "https://github.com/lwm/tasty-discover.git"
      commit: "HEAD"
    extra-dep: true

  - location:
      git: https://github.com/toddmohney/github.git
      commit: bbe1ddfe53a5dc4e1ff7fa17c49a39544cc3b6dd
    extra-dep: true

extra-deps:
  - "tasty-th-0.1.4"

flags: {}

extra-package-dbs: []
